#include <iostream>
#include <limits>
#include <numeric>
#include <sstream>
#include <filesystem> 
#include <vector>
#include <string>
#include <fstream>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime> 
#include <chrono>
#include <random>
#include <iomanip>
#include <cstring>
#include <algorithm>
#include <unordered_set>
#include <utility>
#include <functional> 


using std::cin;
using std::cout;
using std::endl;
using std::vector;
using std::string;
using std::cerr;
using std::move;
using std::to_string;
using std::stringstream;
using std::setprecision;
using std::fixed;
